import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import CitySelector from '../commonComponents/citySearch/CitySelector'
import HomeContainer from '../components/HomePage'
import styles from '../styles/Home.module.css'

// city API being called from here


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>City App</title>
        <meta name="description" content="City App Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CitySelector />
        <HomeContainer />
    </div>
  )
}

export default Home;
